name: Produce an artifact

on:
  - deployment
  - workflow_dispatch

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/hospital-*.jar target/hospital-${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: HospitalAPI
          path: staging
          retention-days: 0
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automatic release ${{ github.run_number }}"
          files: staging/*.jar